name: Test FVE GitHub output

on: [workflow_dispatch]

jobs:
  Export-To-GitHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./gh-fortify-sast.sarif
